#spring:
#    data:
#        elasticsearch:
#            cluster-name: gwf
#            cluster-nodes: 127.0.0.1:9300
#            properties:
#              path:
#                logs: ./elasticsearch/log #elasticsearch日志存储目录
#                data: ./elasticsearch/data #elasticsearch数据存储目录